[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm ci --only=production',
  'npx prisma generate'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm run start:prod'

[variables]
NODE_ENV = 'production'
